### ISSUE TITLE
we have many more than 1 features directories

### ISSUE THREAD

**Issue by andyglick** [temyers/cucumber-jvm-parallel-plugin#14]
Our project has many features directories, and in addition there are some nested features directories, so under /features/ there are the names of all of the subdirectories and within them there are feature files as well as directories containing feature files. Is making cucumber-jvm-parallel-plugin more flexible in this direction something that you would consider taking on, or should we just put together an implementation and submit  a pull request?

**Comment by temyers** [comment]
I have used the cucumber-jvm-parallel-plugin with nested feature files in the same way you describe.  However, I'd expect that these are all nested under a common ancester (e.g. src/test/resources/features).  This directory is what you specify in the plugin and it will find all feature files under there.

Is there a specific scenario where the current implementation doesn't work?  If so, if you can provide a test case then I can review and consider

**Comment by temyers** [comment]
@andyglick - Is this still an issue for you or can I close?

**Comment by vincent-fuchs** [comment]
I think I have the same issue. Here's the folders hierarchy I have :

    src/test/resources/com/myproject
                         |
                   domain1 --> 1.feature
                         |     2.feature
                   domain2 --> 3.feature
                               4.feature 

If I configure featuresDirectory with src/test/resources/com/myproject/ , no feature file is found.

If I configure featuresDirectory with src/test/resources/com/myproject/domain1/ , then the 2 feature files are found, and 2 test classes are generated, but no test gets executed because in Parallel01IT, cucumberOptions are like this :

    @CucumberOptions(strict = true,
        features = {"classpath:domain1/1.feature"},
     ...

at execution, 1.feature is not found, and no test gets executed. 

The only way I've been able to make it work is by moving all my feature files in a common src/test/resources/features directory, and configuring it the same way as in the documentation.

**Comment by temyers** [comment]
Ok, I'll look into it.

**Comment by temyers** [comment]
From an initial look (and I'll need to create a test case to confirm), the classpath is configured from the root of the classpath.  Therefore a folder within `/src/test/resources`.  So in your example @vincent-fuchs, the features directory should be `src/test/resources/com`.

**Comment by vincent-fuchs** [comment]
yes, it works, thanks !

**Comment by temyers** [comment]
Closing as I don't think this is an issue.
