### ISSUE TITLE
feature Directory path not set correctly in Runner file

### ISSUE THREAD

**Issue by saikrishna321** [temyers/cucumber-jvm-parallel-plugin#17]
@temyers  

i have my feature files inside multiple directory as below **/src/test/resources/com/automationrhapsody/cucumber/parallel/tests/wikipedia**

in my pom.xml if i specify the entire path it does not work as expected

```
                     <configuration>
                         <glue>com.automationrhapsody.cucumber.parallel.tests.wikipedia</glue>
                          <featuresDirectory>src/test/resources/com/automationrhapsody/cucumber/parallel/tests/wikipedia</featuresDirectory>
                            <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
                            <format>json,html</format>
                            <tags>"~@ignored"</tags>
                        </configuration>
```

Genrerated Runner class is 

```
@RunWith(Cucumber.class)
@CucumberOptions(strict = true,
    features = {"classpath:wikipedia/main-page.feature"},
    format = {"json:target/cucumber-parallel/2.json", "html:target/cucumber-parallel/2.html", "pretty"},
    monochrome = false,
    tags = {"~@ignored"},
    glue = { "com.automationrhapsody.cucumber.parallel.tests.wikipedia" })
public class Parallel02IT {
}
```

classpath is in-correct it should have been src/test/resources/com/automationrhapsody/cucumber/parallel/tests/wikipedia/main-page.feature

**Comment by temyers** [comment]
I have reproduced the problem.  However, the fix would not be trivial, potentially causing a breaking change.

Is there a reason that you cannot use the top level directory within the resources folder?

```<configuration>
                         <glue>com.automationrhapsody.cucumber.parallel.tests.wikipedia</glue>
                          <featuresDirectory>src/test/resources/com</featuresDirectory>
                            <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
                            <format>json,html</format>
                            <tags>"~@ignored"</tags>
                        </configuration>
```

**Comment by saikrishna321** [comment]
@temyers i can use the top level directory but what if feature files are at different folder

for Example:
com/automationrhapsody/cucumber/parallel/tests/wikipedia
org/
homepage/

**Comment by bhattankit** [comment]
@temyers - Does the feature files have to be located in src/test/resources? Also I have a feature file there with 1 tag and in my <tags> input to the plugin I am passing more than 1 tags.

I am getting the below error:

None of the features at [classpath:features/sample.feature] matched the filters: [@ComponentTest, @CompTest, ~@wip]

**Comment by temyers** [comment]
As a general rule, I think that feature files should all be contained under a common root folder (e.g. src/test/resources/features).

If you have multiple folders it indicates that the project is possibly bloated and should be split up.  In your example above, you have tests spanning `com/` `org`.  Whilst the groupings are effectively arbitrary, the names suggest you are testing two different things (due to the different packages) and therefore the project should perhaps be split up.

Feature files don't have to be located under `src/test/resources`, but they *must* be on the classpath.  So `src/main/resources` would be an alternative, or in a dependent JAR file.  This is another reason to have a standard root directory for features.  Whilst I do not recommend to use `src/main/resources` or import feature files from a dependency, it is possible.  However I would consider it a code smell.

Regarding the last point.  Please check that the boolean logic specified in the tags configuration is correct.
Refer to: https://github.com/cucumber/cucumber/wiki/Tags
And see the samples under src/it/junit for AND/OR when filtering tags.

**Comment by tadasleiga** [comment]
Sorry for starting up an old thread, but I preferred this rather then creating a new one since the problem is the same.

In our project each module have their own .feature files stored in different folders so that we could run tests separately. This could be easily done by just passing module name to maven environment and filter .feature files with `<featuresDirectory>src/test/resources/features/${project.module}</featuresDirectory>` rather than adding annotations to every .feature file (we have them ~200) and filter by tags.

Unfortunately current implementations doesn't work in that way. Do you think this is a bad way of using this plugin? Can you recommend some other ways to achieve the same goal?

**Comment by tadasle** [comment]
@temyers bump

**Comment by temyers** [comment]
@tadasle Sorry for the slow reply.

As mentioned in my comment above, I generally thing that feature files should live under a common directory.

In a [multi-module project](https://maven.apache.org/guides/mini/guide-multiple-modules.html), I would expect that each module should contain it's own feature files and tests.  If you're sharing steps between modules, then I'd question whether you are missing something in your project structure/domain model - is the packaging correct.  This would give you much more control over running tests.

As above, supporting arbitrary folders for the feature files is actually non trivial and would add unnecessary complication to the plugin IMO.  Therefore, I'm going to state this as a limitation in the README - the `<featuresDirectory>` tag must point to a **folder in the root of the runtime classpath**.

However, having said all that, in your case, you could achieve the desired result by removing the features directory.

`<featuresDirectory>src/test/resources/${project.module}</featuresDirectory>`

**Comment by murthis** [comment]
It would be good if we are able to execute the scripts/features files by sub folder as one of the good way to group the testcase/feature is  by  sub folder. I would be happy if you have add the feature to execute the feature files in the sub folder like src/test/resources/features/subfolder. Also, cucumber itself supports the feature files in any folders.

**Comment by ajmera25** [comment]
Sorry for commenting in old issue. 

Currently I am having features under many subfolder for example :- src/test/resources/features/subfolder1 or src/test/resources/features/subfolder2. I want is that runner generated should also be under subfolder like . ex- src/test/java/subfolder1 or src/test/java/subfolder2. Can it be possible??
