### ISSUE TITLE
Empty json file generated while running in parallel

### ISSUE THREAD

**Issue by hemachandraraok** [temyers/cucumber-jvm-parallel-plugin#98]
Hi, I am running 26 feature files in parallel with fork count 5. 
26 json files are generated as reports, but few of them are empty. the number of empty jsons vary from 5 to 10, and the feature files corresponding to these json also vary from execution to execution.

Can you please let me know if there are any known issues.

**Comment by temyers** [comment]
Hi @hemachandraraok.  

There are no known issues around this but possible causes:
* Are those files being skipped for any reason (e.g. tags)
* Could it be an accurrance of issue #94 

Are you able to demonstrate the issue in a sample project?

**Comment by hemachandraraok** [comment]
It could be an occurence of #94 . I m using ~manual tag in plugin in pom.xml to skip certain scenarios.

Also, I am specifying the features to run from commandline using -Dcucumber.options="path/to/features". So should we not use any cucumber options from command line at all?

**Comment by temyers** [comment]
You should be able to use `-Dcucumber.options` - the parallel plugin parses the options, using the same mechanism as Cucumber, to generate the runners.  However, #94 is a special case, caused by limitations in the Cucumber runner itself.

Can you post an example project, or post output from a parallel build to help narrow down the issue?

**Comment by temyers** [comment]
Could this be caused by issue #77?

Please try updating to version `4.0.0`.
